name: Lock branch

on:
  workflow_dispatch:  # 手動でトリガー

jobs:
  update-branch-protection:
    runs-on: ubuntu-latest

    steps:
      - name: Update Lock Branch setting
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GIT_PAT }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const branch = "lock/test2"; // ロック対象のブランチ

            // 現在のブランチ保護ルールを取得
            const protection = await github.rest.repos.getBranchProtection({
              owner,
              repo,
              branch,
            });


            // 必要なフィールドを更新
            const updatedProtection = {
              allow_force_pushes: false, // 強制プッシュを禁止
              allow_deletions: false, // ブランチ削除のロック
            };

            console.log('%o', {
              owner,
              repo,
              branch,
            } );

            console.log('%o', {
              enforce_admins: protection.data.enforce_admins.enabled,
              required_pull_request_reviews: protection.data.required_pull_request_reviews,
              required_status_checks: protection.data.required_status_checks.enabled,
              restrictions: protection.data.restrictions.enabled,
            } );

            console.log('%o', {
              allow_force_pushes: updatedProtection.allow_force_pushes, // 更新内容
              allow_deletions: updatedProtection.allow_deletions, // 更新内容
              block_creations: protection.data.block_creations.enabled,
            } );

            console.log('%o', {
              required_conversation_resolution: protection.data.required_conversation_resolution.enabled,
              lock_branch: true, // 更新内容
              allow_fork_syncing: protection.data.allow_fork_syncing.enabled 
            } );


            // 更新リクエスト
            await github.rest.repos.updateBranchProtection({
              owner,
              repo,
              branch,
              enforce_admins: protection.data.enforce_admins.enabled,
              required_pull_request_reviews: protection.data.required_pull_request_reviews,
              required_status_checks: protection.data.required_status_checks.enabled,
              restrictions: protection.data.restrictions.enabled,
              allow_force_pushes: updatedProtection.allow_force_pushes, // 更新内容
              allow_deletions: updatedProtection.allow_deletions, // 更新内容
              block_creations: protection.data.block_creations.enabled,
              required_conversation_resolution: protection.data.required_conversation_resolution.enabled,
              lock_branch: true, // 更新内容
              allow_fork_syncing: protection.data.allow_fork_syncing.enabled 
            });

            console.log(`Branch protection for '${branch}' successfully updated.`);
