name: Lock branch

on:
  workflow_dispatch:  # 手動でトリガー

jobs:
  update-branch-protection:
    runs-on: ubuntu-latest

    steps:
      - name: Update Lock Branch setting
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GIT_PAT }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const branch = "lock/test2"; // ロック対象のブランチ

            // 現在のブランチ保護ルールを取得
            const protection = await github.rest.repos.getBranchProtection({
              owner,
              repo,
              branch,
            });

            console.log('%o', protection );

            // 必要なフィールドを更新
            const updatedProtection = {
              allow_force_pushes: false, // 強制プッシュを禁止
              allow_deletions: false, // ブランチ削除のロック
            };



            // 更新リクエスト
            await github.rest.repos.updateBranchProtection({
              owner,
              repo,
              branch,
              required_status_checks: null,
              enforce_admins: protection.data.enforce_admins.enabled || null,
              required_pull_request_reviews: {
                dismissal_restrictions: {
                  
                },
                dismiss_stale_reviews: protection.data.required_pull_request_reviews.dismiss_stale_reviews || false,
                require_code_owner_reviews: protection.data.required_pull_request_reviews.require_code_owner_reviews || false,
                required_approving_review_count:  protection.data.required_pull_request_reviews.required_approving_review_count,
                require_last_push_approval :  protection.data.required_pull_request_reviews.require_last_push_approval,
              },
              restrictions: { // "Only organization repositories can have users and team restrictions"
                  // users: [],
                  // teams : [],
                  apps : []
              },
              lock_branch: true, // 更新内容
              allow_force_pushes: updatedProtection.allow_force_pushes, // 更新内容
              allow_deletions: updatedProtection.allow_deletions, // 更新内容
            });

            console.log(`Branch protection for '${branch}' successfully updated.`);
